### ISSUE TITLE
To be able to complete QA properly I need to know these things

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#32]
**Need these things to work:**
- [x] Customize 
- [x] Widgets
- [x] Background

Currently, these items all go to white screen:
![screen shot 2015-04-09 at 10 11 42 am](https://cloud.githubusercontent.com/assets/7047954/7068521/f19cce7e-dea0-11e4-9c24-dc18758b6aea.png)

**I need to know these questions:**
- [x] Are there designs to show me what the theme is suppose to look like?  Example of why I need this: The QA list mentions a Carousel where would that go?  
- [x] I need to know the intended functionality, otherwise I'm just guessing that's right. Please provide more information of the functionality, the below questions include some of the info that will be helpful.
- [x]  What browsers are compatible?
- [x]  Any limitations I should know about file size wise?
- [x] How many menu areas are there?  
- [x] How is the mobile menu intended to work? 
- [x] Where is the Carousel suppose to be located?  What is the goal of the Carousel? 
- [x] What are the reading settings suppose to be?  With a Carousel it seems it would designate a homepage. 
  ![screen shot 2015-04-09 at 10 20 35 am](https://cloud.githubusercontent.com/assets/7047954/7068686/1881712e-dea2-11e4-9f6d-1cff3c275cc9.png)
- [x] What are the dimensions of the theme and recommended upload size? Ex: Header, Carousel, Logo, Featured Image size
- [x] Where are the widget areas located?
- [x] How to create the sermon listing page?  Do you choose a template and if so, which one?
- [x] How do events work?  Do they require any plugin? Do you have to create an Events page using a certain template?
- [x] How to create the blog listing page?  Do you choose a template and if so, which one?
- [x] How does the user place their avatar?  Does it use gravatar? 
- [x] How to create the location listing page?  Do you choose a template and if so, which one?
- [x] How to create the staff listing page?  Do you choose a template and if so, which one?
- [x] How does the social menu work? Create a new menu?

**Comment by imbradmiller** [comment]
@garand Answer these today please.

Thanks,
Brad

**Comment by garand** [comment]
Will do.

**Comment by angela-crist** [comment]
@garand Just wanted to confirm these will be done today so I know if I should put QA in my day tomorrow. Thanks!

**Comment by garand** [comment]
Yes, I'll have an answer for everything, but I can't guarantee that I will have a fix in place for the pages that are broken.

**Comment by garand** [comment]
The theme isn't including a carousel at this point. We may add it in the future.

> What browsers are compatible?

IE 9+, Latest versions of the rest.

> Any limitations I should know about file size wise?

None that I am aware of.

> How many menu areas are there?

Two. Primary and Social.

> How is the mobile menu intended to work?

It should be the primary menu hidden behind some type of menu icon.

> Where are the widget areas located?

Sidebar
Secondary Sidebar (only for three-column layouts)
Footer Left/Center/Right

> How does the user place their avatar?

Just like every WordPress site, managed via Gravatar.

> Sermons/Events/Locations/Staff pages

These all use WordPress post type archive templates. You can add them to the menu through this plugin, which should already be installed. https://wordpress.org/plugins/post-type-archive-links/

**Comment by angela-crist** [comment]
@garand Thanks for answering these questions. Looks like some of the questions were not completely answered please clarify:

> The theme isn't including a carousel at this point. We may add it in the future.
> I believe this in response to:
- [x] Are there designs to show me what the theme is suppose to look like? Example of why I need this: The QA list mentions a Carousel where would that go?

The carousel was just one example.  The main question is - Are there designs of what the theme is suppose to look like?  I'm coming in with no previous knowledge so I don't know what the look, features and functionality should work, please provide insight and or designs. 

> In response to your social menu and primary menu.
- [x] Where should the social menu show?

> In response to your answer to the how the mobile menu should work.  
- [x] I'm looking more for how does it work as in is there a different menu, like the structure of Yumblog or is it just the primary menu? Basically, is there anything different I need to know about?

> You did not respond to the Front page display, what should that be? See...
- [x] What are the reading settings suppose to be? With a Carousel it seems it would designate a homepage. (see image above)

> You didn't see an answer for what the dimensions of the theme and recommended upload size: 
- [x] What are the dimensions of the theme and recommended upload size? Ex: Header, Carousel, Logo, Featured Image size

> In response the the post type for pages all of the specific pages (Sermons, Events, Locations, Blog, and Staff) use the archive template?  
- [x] That is not how Uplifted works:  http://churchthemes.helpscoutdocs.com/article/17-creating-main-pages so I just need to clarify what template to choose when creating these pages. 

> Regarding Events, we will just use the CTC events?  
- [x] No plugin needed? Do we suggest an events specified plugin, like The Events Calendar?

> I didn't see a response for how the social menu works?
- [x] Do I create a new menu or does it work another way?

**Comment by angela-crist** [comment]
For QA to begin here's what is needed:
- [x] Answers to questions above (see most recent comment and unchecked boxes in first comment
- [x] Get Customize area to work (also in checkboxes above in first comment)
- [x] Ability to see demo currently not viewable:
  ![screen shot 2015-04-21 at 11 44 20 am](https://cloud.githubusercontent.com/assets/7047954/7256838/743dd2e2-e81f-11e4-91d4-530c2851f0dc.png)

FYI: @garand @imbradmiller @chriswallace

**Comment by garand** [comment]
> Are there designs of what the theme is suppose to look like?

No, there are no designs for this theme. The goal is to be quite minimal and have designed styles on top of it. It is following the same visual design of [Basis](http://basiswp.com).

> Where should the social menu show?

Right aligned in the footer.

> Mobile Menu?

There is no separate mobile menu currently, it just uses the primary menu.

> What are the reading settings suppose to be?

Just latest posts is fine. If someone wanted a custom template, they could set that.

> What are the dimensions of the theme and recommended upload size?

These haven't been decided yet. Since sizes for images and logos may be different between themes, I haven't decided on a good size constraint for images yet.

> Archive pages for Sermons, Events, Locations, Staff

You don't create these pages. They are generated automatically.

> Events Plugin?

I don't see why you would need a plugin, we support events rather well right out of the box.

> Social Menu?

It's a new menu, just make sure to set the menu location to "Social Menu".

**Comment by angela-crist** [comment]
@garand Thanks so much for those clarifications! That was very helpful. 
Does this list:  https://github.com/ChurchThemes-WP/rock-framework/wiki/QA-Checklist include all of the features / functionality you would like me to QA?

The only remaining items to completely QA include getting these items to work:
- [x] Customize 
- [x] Widgets
- [x] Background

**Comment by angela-crist** [comment]
Awesome!! All is working! I will get my QA on :)
