### ISSUE TITLE
Intro Text, where to add?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#34]
This is included in the QA list and I'm assuming this means text above the blog.  I'm just guessing since I don't have anything to go off of.

I'm assuming it's like Largo:
![screen shot 2015-04-24 at 12 09 19 pm](https://cloud.githubusercontent.com/assets/7047954/7323181/c5c23cae-ea7a-11e4-8f29-c061db047b81.png)

Where would I add this?  Does this need to be added?

**Comment by garand** [comment]
Let's scratch this for now. I think that Faith Builder will handle a lot of this. If we need to add it later, we can.
