### ISSUE TITLE
Customize does not show a preview of the following layouts...

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#35]
![screen shot 2015-04-24 at 12 28 56 pm](https://cloud.githubusercontent.com/assets/7047954/7323591/9fef7afc-ea7d-11e4-9ea2-965cc3ffd523.png)

Not sure if this is possible or not I just know that the customer expects to see the preview and when they don't they assume it's broken. 

It does work when you click save and refresh, just can't see in the preview.

**Comment by garand** [comment]
This works now.
