### ISSUE TITLE
Search widget needs some styling if you add text 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#38]
![screen shot 2015-04-24 at 2 11 04 pm](https://cloud.githubusercontent.com/assets/7047954/7325353/d80c11da-ea8b-11e4-8c48-dcc6e35dd388.png)

It goes right to the end of the widget box

**Comment by garand** [comment]
![screen shot 2015-06-11 at 10 19 44 am](https://cloud.githubusercontent.com/assets/82437/8109178/666434f0-1023-11e5-80c3-5cdd6cc8c99e.png)
