### ISSUE TITLE
Video / Audio Download

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#39]
I'm assuming you can only download if saved directly to the site.  Just wanted to let you know when saved by an outside source (YouTube, SoundCloud) it will not show the buttons.  

![screen shot 2015-04-30 at 1 28 26 pm](https://cloud.githubusercontent.com/assets/7047954/7418598/f9e8d9ea-ef3c-11e4-8b09-d6c9f65ceac4.png)

**Comment by garand** [comment]
Correct, you can only download if it's uploaded via WordPress.
