### ISSUE TITLE
Will there by a Sermon Listing page as outlined in QA list?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#40]
Is the Sermon listing page only the blog like format of this page: http://demo.churchthemes.net/rock-framework/sermons/

I know I have a lot of customer's ask for just a listing as well. Just want to know what the plan is for this page.

**Comment by garand** [comment]
Yes, the page to view sermons is just the `/sermons` page. What is different between that and the "listing" your referring to?
