### ISSUE TITLE
Full text sermon provided - what is that suppose to do? I don't see this anywhere

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#44]
![screen shot 2015-04-30 at 1 45 46 pm](https://cloud.githubusercontent.com/assets/7047954/7418892/597c3d96-ef3f-11e4-9bcb-4bf1106dad41.png)

**Comment by garand** [comment]
We don't currently do anything with this, but it's useful meta information to have for possibly generating podcast feeds with show notes, or providing downloadable transcripts of sermons as an option in the future.
