### ISSUE TITLE
What is categories referring to in Sermons meta?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#46]
I don't see this within the sermons area?

Is this referring to books, series, and speakers?

**Comment by garand** [comment]
I don't see categories anywhere, what are you talking about?

**Comment by angela-crist** [comment]
Hmmm I can't find what I was referring to either...closing

**Comment by angela-crist** [comment]
![screen shot 2015-07-01 at 10 18 36 am](https://cloud.githubusercontent.com/assets/7047954/8456614/90443e3e-1fda-11e5-82a2-dd1cdf4355ce.png)
I found it...It was something you included in the QA list...what where you referring to?

**Comment by garand** [comment]
Ah, disregard. That was a formatting error when I put the QA list together.
