### ISSUE TITLE
Add something to the top right side of the menu (service times, sub-menu)

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#48]
http://lift.d.pr/1ji3G/1H6vEwzG
Chat with Chris to see his vision for this prior to starting. 

Per @chriswallace via the Faithmade Project Plan meeting 5/14

**Comment by garand** [comment]
How does this look?

![screen shot 2015-06-11 at 11 40 43 am](https://cloud.githubusercontent.com/assets/82437/8111242/b815f6e8-102e-11e5-9c6e-723cea4f4877.png)

**Comment by garand** [comment]
How does this look?

**Comment by angela-crist** [comment]
Looks good! 
Do we need to account for content that makes the header too long?

Ex:
![screen shot 2015-07-01 at 10 10 19 am](https://cloud.githubusercontent.com/assets/7047954/8456458/8d986936-1fd9-11e5-8a59-37e1c4a1f537.png)

**Comment by garand** [comment]
Let's close this for now and just note that in the documentation.
