### ISSUE TITLE
Add support for Colorcase

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#49]
Discussion here:  https://basecamp.com/1761770/projects/9345528/todos/177508345

**Comment by angela-crist** [comment]
- [x]  Make sure to make it auto deploy
- [x]  Install Colorcase plugin

**Comment by angela-crist** [comment]
Thanks @garand

**Comment by angela-crist** [comment]
@garand Colorcase is working awesome! Here's a few notes/updates needed: 
- [x]  Remove Colors section from Customize http://lift.d.pr/14q2Y/3jhd7fcO This works but doesn't work if you choose the items in the new 'Theme Colors' area
- [ ]  Add more color palettes (ask Chris)
- [x] Sidebar colors section in customize were not coloring the secondary sidebar:  http://lift.d.pr/wN5U/5MwqASuf
- [x] Could we add an option to change the color of the flyout of the menu. Where the black is here:  http://lift.d.pr/13S2z/2hC7KygB
- [x] Add ability to change color of comment area

**Comment by angela-crist** [comment]
@garand I'm no longer seeing a second sidebar when choosing layouts with that option. Can you take a look. http://lift.d.pr/1eiAU/3BT7LZh5

**Comment by garand** [comment]
Sure, can you create it as a new issue though? It's unrelated to Colorcase.

**Comment by angela-crist** [comment]
cool will do

**Comment by angela-crist** [comment]
@garand Let me know when #50 is complete and I will QA 
- [x] Sidebar colors section in customize were not coloring the secondary sidebar:  http://lift.d.pr/wN5U/5MwqASuf

**Comment by garand** [comment]
This should work fine once you add widgets to the secondary sidebar.

**Comment by angela-crist** [comment]
Awesome @garand I will QA again.

**Comment by angela-crist** [comment]
Works great! Thanks!
