### ISSUE TITLE
Second sidebar no longer is showing with layouts with that option. 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#50]
Can you take a look. http://lift.d.pr/1eiAU/3BT7LZh5

**Comment by garand** [comment]
@angela-crist Make sure you have widgets configured in the secondary sidebar.

**Comment by angela-crist** [comment]
Ok I can see the second sidebar now but when I try to go to the other layouts it seems to be stuck and stays showing all 3 columns. 

http://lift.d.pr/1kyLl/3UiRfo0h

It does work with the customize area though. I would think the pages would work the same.

**Comment by garand** [comment]
Where are you seeing this at? It's working fine on this page for instance. http://demo.churchthemes.net/rock-framework/three-column-sidebar-content-sidebar/

**Comment by angela-crist** [comment]
It seems it wasn't showing on the customizer only when I would click collapse would I see it:  http://lift.d.pr/Dt9D/zoLewzvS

**Comment by garand** [comment]
That's because it's dropping them below the content since the customizer pane is too small.
