### ISSUE TITLE
Event - Recurrence where can you tells it's recurring?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#52]
![screen shot 2015-07-01 at 10 29 04 am](https://cloud.githubusercontent.com/assets/7047954/8456853/0648ba6e-1fdc-11e5-9a27-e2a94735b189.png)

Is there a calendar view or does the posting just continuing to show and the date continues to change?

**Comment by garand** [comment]
I'm not sure, I've not tested that feature. Could you create a recurring one and see what happens?

**Comment by angela-crist** [comment]
The recurring event was there. It doesn't do anything differently. Not sure what the field is or perhaps it is not functioning and you have do add that add on with the Church Theme Content Plugin.  

Here's my example recurring event;  http://demo.churchthemes.net/rock-framework/events/sunday-services/

**Comment by garand** [comment]
@angela-crist I remember us talking about this yesterday, what did we end up deciding to do?

**Comment by angela-crist** [comment]
We need to integrate this into Faithmade but it will require us to write this code fresh. I've included this in the Faithmade repo: https://github.com/LiftUX/faithmade/issues/47
