### ISSUE TITLE
Events - is there a calendar view as well?

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#54]

**Comment by garand** [comment]
What events view are you talking about? The actual events page, widget, or the Faith Builder module?

**Comment by angela-crist** [comment]
I think there should be a view of the events on a calendar highlight the day like it does for blog:

<img width="220" alt="screen shot 2015-07-10 at 4 36 16 pm" src="https://cloud.githubusercontent.com/assets/7047954/8628538/db038ef4-2721-11e5-8f29-0c209b6c38f8.png">

This is probably an enhancement.  Is there anything like this with what we currently have?

**Comment by garand** [comment]
Let's plan on adding that down the road further as it will require more work.
