### ISSUE TITLE
Featured post has two buttons for read more

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#55]
![screen shot 2015-07-01 at 10 43 12 am](https://cloud.githubusercontent.com/assets/7047954/8457197/000d3984-1fde-11e5-95da-8119b6b8fa49.png)

**Comment by angela-crist** [comment]
This only shows when the content is longer.  The Image is also shortened. 

![screen shot 2015-07-01 at 10 46 09 am](https://cloud.githubusercontent.com/assets/7047954/8457273/6a992452-1fde-11e5-8007-b473075d09cc.png)

**Comment by garand** [comment]
I can't reproduce this.

@angela-crist If you can link me to a demo site that is doing this, I'll take another look.

**Comment by angela-crist** [comment]
This was a test here:  http://demo.churchthemes.net/rock-framework/ and only happened when content was too long. 

Does Praise also have a featured post look like this?

**Comment by garand** [comment]
Yea, just add the tag you want to be featured in the customizer under featured content. Can you reproduce this on http://praisedemo.faithmade.com so that I can test it out.

**Comment by angela-crist** [comment]
Is that a Jetpack thing?  We don't have that installed on the Praise demo: https://praisedemo.faithmade.com/wp-admin/plugins.php  I don't think we are utilizing Jetpack for Faithmade, correct me if I'm wrong. 

http://lift.d.pr/10qH7/UGUCfl3q

Let me know how to reproduce creating the featured post using Praise.

**Comment by angela-crist** [comment]
@garand Let me know how to reproduce creating featured post using Praise (see last comment)

**Comment by angela-crist** [comment]
@garand I saw that Chris said we aren't using Featured image. Is this issue still relevant them? If so, let me know how to test.

**Comment by garand** [comment]
@angela-crist Where did he say that?

**Comment by angela-crist** [comment]
Oh I meant I saw Chris said we aren't using Jetpack...whew thanks for questioning that previous comment. Here's a link to the convo: 
![screen shot 2015-08-11 at 12 20 07 pm](https://cloud.githubusercontent.com/assets/7047954/9203157/65301cae-4023-11e5-885c-8110fa34b749.png)

**Comment by angela-crist** [comment]
Let me know how to test to produce the featured image since we aren't using Jetpack. @garand

**Comment by garand** [comment]
Due to us not using Jetpack, let's close this out for the moment and we can consider adding it as another feature later.

**Comment by angela-crist** [comment]
so currently there is no way to make a post featured, correct?

**Comment by garand** [comment]
Correct. Let's put it in the enhancement category for now.

**Comment by angela-crist** [comment]
great thanks!!
