### ISSUE TITLE
Locations - Times - could we add some text to describe what time they could show there

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#57]
![screen shot 2015-07-01 at 10 55 34 am](https://cloud.githubusercontent.com/assets/7047954/8457512/d01829b2-1fdf-11e5-8728-f4a2497a3da7.png)

Perhaps add text that says...

Add sermon times or hours of operation

**Comment by garand** [comment]
Completed with [this commit](https://github.com/faithmade/churchthemes/commit/587939e144dae498f74af3f64c12e88808f75f95).
