### ISSUE TITLE
People - It doesn't show the url's anywhere

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#61]
![screen shot 2015-07-01 at 11 06 47 am](https://cloud.githubusercontent.com/assets/7047954/8457747/4a41acda-1fe1-11e5-8fcb-17ed0b0154fe.png)

![screen shot 2015-07-01 at 11 07 13 am](https://cloud.githubusercontent.com/assets/7047954/8457758/5ac7e54c-1fe1-11e5-8a12-dfcecff5c9c9.png)

**Comment by garand** [comment]
I'm not really sure what the URLs are even supposed to be for. Do you have an idea?

**Comment by garand** [comment]
I'm considering removing the URL field from the admin. Is anyone opposed to that?

**Comment by angela-crist** [comment]
I think it's great to allow them to show their site and social links if they want. http://churchthemes.com/guides/user/content/people/#people-page

I vote to keep

**Comment by garand** [comment]
Okay, I'm easily convinced. Thanks for the link.
