### ISSUE TITLE
People - Groups do not show anywhere on the listing page or individual page

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#62]
![screen shot 2015-07-01 at 11 09 03 am](https://cloud.githubusercontent.com/assets/7047954/8457814/9b6aa1b6-1fe1-11e5-999b-25bcea1ffdd9.png)

**Comment by garand** [comment]
What do you envision seeing for this on the front-end? A sub-nav of sorts to only see those groups, staff members sorted by group on the page, or something else?

**Comment by angela-crist** [comment]
Yeah I'm thinking a sub-nav that will show the different groups categories leading to a page only showing that category

**Comment by garand** [comment]
Due to the way the archive pages are automatically generated, we can't easily add the groups. I think this may be something we will look into when we figure out how to create custom archive pages for the different church post types.
