### ISSUE TITLE
Created a page with a form / filling out form leads to an error:

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#64]
![screen shot 2015-07-01 at 11 14 54 am](https://cloud.githubusercontent.com/assets/7047954/8457976/79874c42-1fe2-11e5-9b5b-9b7f79cae9db.png)

**Comment by garand** [comment]
@chriswallace I believe this is your territory.

**Comment by garand** [comment]
@angela-crist Can you check to see if this is still an issue?

**Comment by angela-crist** [comment]
@garand Yea it works now.  I don't know if we will offer that to customer but it works :)

http://lift.d.pr/1j6HR/2rGKCFgt
