### ISSUE TITLE
What is the calendar widget suppose to do?  It doesn't show anything

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#65]
![screen shot 2015-07-01 at 11 17 56 am](https://cloud.githubusercontent.com/assets/7047954/8458053/d96dbfb0-1fe2-11e5-9e29-72691b2519f0.png)

**Comment by garand** [comment]
If I remember correctly, it highlights days that have posts on them and when you click on the day it takes you to an archive page that lists all of the posts for that day.

**Comment by angela-crist** [comment]
ok gotcha. Is there a calendar view like that for the events?

**Comment by garand** [comment]
No, but it's something we can add down the road. (#54)
