### ISSUE TITLE
Footer - where do you edit that copyright text

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#66]
I looked in customizer and could not find it

![screen shot 2015-07-01 at 11 20 14 am](https://cloud.githubusercontent.com/assets/7047954/8458105/2b21c8ec-1fe3-11e5-8342-21cedc2d8c90.png)

![screen shot 2015-07-01 at 11 20 37 am](https://cloud.githubusercontent.com/assets/7047954/8458118/3b145b3e-1fe3-11e5-9f2c-d14efc8cd922.png)

**Comment by garand** [comment]
I believe this is hard coded right now. I can add a text field for this.

**Comment by angela-crist** [comment]
Yes please but keep in mind we still need to define what the customer will be able to edit in the footer
