### ISSUE TITLE
Two Column - Content / Sidebar is currently showing 3 columns

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#67]
http://demo.churchthemes.net/rock-framework/18-2/

![screen shot 2015-07-01 at 11 33 15 am](https://cloud.githubusercontent.com/assets/7047954/8458417/fe912b18-1fe4-11e5-9ff7-54cf0af73630.png)

**Comment by garand** [comment]
That page wasn't configured properly. I just had to go into the admin and change the template that it was set to.
