### ISSUE TITLE
Create feature post functionality 

### ISSUE THREAD

**Issue by angela-crist** [faithmade/rock#73]
We discovered we aren't using Jetpack #55 , so let's decide if we want to do this and if so how?

This is low priority and is just considered an enhancement, it is not included in Beta unless we decide otherwise.

**Comment by angela-crist** [comment]
@garand Do you want to include this in beta?

**Comment by angela-crist** [comment]
@garand I think this would be good to include feature post functionality to the homepage as it is in self-hosted. Please provide an ETA.

**Comment by angela-crist** [comment]
@garand Let me know the ETA here if you think we should complete for Faithmade.  Let me know your thoughts.

**Comment by garand** [comment]
Let's do this as sticky posts so we're using built in functionality. Can you test Rock's sticky posts functionality and let me know how that works and what, if anything, needs design?

**Comment by angela-crist** [comment]
Sound good :+1:
