### ISSUE TITLE
Fix phone fields

### ISSUE THREAD

**Issue by chriswallace** [faithmade/rock#78]
It looks like we missed a style for inputs for telephone numbers. Please verify that we cover all HTML5 form styles.

http://lift.d.pr/1bJSK

**Comment by angela-crist** [comment]
@garand Please confirm that you can complete this by Jan. 7th

**Comment by garand** [comment]
Confirmed.

**Comment by angela-crist** [comment]
:+1: Thanks!

**Comment by angela-crist** [comment]
Just checking in on this to make sure we are good for a Friday push

**Comment by garand** [comment]
Yup!

**Comment by angela-crist** [comment]
This is included in tomorrow's QA and deployment.
**Note**: QA will complete at 3PM tomorrow.

**Comment by angela-crist** [comment]
@garand This is still good to go today, correct?
